const fs = require('fs');
let content = fs.readFileSync('App.tsx', 'utf8');
content = content.replace(
  "const [activeTab, setActiveTab] = useState('home');",
  "const [activeTab, setActiveTab] = useState('home');\n  const [theme, setTheme] = useState(() => localStorage.getItem('app-theme') || 'default');\n\n  useEffect(() => {\n    document.documentElement.setAttribute('data-theme', theme);\n    localStorage.setItem('app-theme', theme);\n  }, [theme]);"
);
content = content.replace(
  '<h3 className="text-[11px] font-black text-[#FDD835] uppercase mb-4 tracking-widest">Preferências</h3>',
  '<h3 className="text-[11px] font-black text-[#FDD835] uppercase mb-4 tracking-widest">Preferências</h3>\n\n                <div className="flex justify-between items-center bg-[#112240] p-4 rounded-xl mb-3">\n                  <div>\n                    <p className="text-sm font-bold text-white uppercase">Aparência</p>\n                  </div>\n                  <select \n                    value={theme} \n                    onChange={e => setTheme(e.target.value)}\n                    className="bg-[#0A1526] text-white text-xs p-2 uppercase font-bold tracking-widest rounded border border-[#233559]"\n                  >\n                    <option value="default">Padrão</option>\n                    <option value="obsidian">Obsidian</option>\n                    <option value="forest">Forest</option>\n                    <option value="wine">Wine</option>\n                    <option value="light">Claro</option>\n                  </select>\n                </div>\n\n                <div className="bg-[var(--bg-card)] p-5 rounded-3xl border border-[var(--border-subtle)] hover:border-[var(--brand)] transition-colors mb-3">\n                   <div className="flex justify-between items-center mb-3">\n                     <h4 className="text-[var(--text-main)] font-semibold uppercase">Exemplo de Tema</h4>\n                     <span className="text-[var(--text-muted)] text-[10px] uppercase font-bold bg-[var(--bg-panel-alt)] px-2 py-1 rounded-md border border-[var(--border-subtle)]">\n                       09:00\n                     </span>\n                   </div>\n                   <p className="text-[var(--text-muted)] text-[11px] mt-1">Pré-visualização do tema atual selecionado.</p>\n                   <button className="mt-4 w-full bg-[var(--brand)] text-[var(--text-inv)] font-semibold uppercase py-2 rounded-xl">\n                     Ver Detalhes\n                   </button>\n                </div>'
);
fs.writeFileSync('App.tsx', content);
